### ISSUE TITLE
What is o3xr2485dmmdi78177v7c33wtu7315.net?

### ISSUE THREAD

**Issue by 3lpsy** [PaulMorris/mind-the-time#14]
I was looking over the source code and found references to o3xr2485dmmdi78177v7c33wtu7315.net. I am curious as to why this domain is being used? Is it just a dummy value?

**Comment by PaulMorris** [comment]
Yeah, it's a dummy value that's used for "only log time and not websites" mode, where time is logged to that dummy domain.
