### ISSUE TITLE
Setting time limits

### ISSUE THREAD

**Issue by hrkrshnn** [PaulMorris/mind-the-time#9]
Hello! I really like this extension. However, it would be really cool if I could get some sort of warning if I exceed spending more than a certain predefined time T on a predefined webpage. For example, say 30 minutes on youtube.com.

I would actually like to implement it myself. But I'm quite new to writing firefox extensions. What do you think about this idea? If it's not too much, could you point me to places in source code that needs to be modified?

**Comment by PaulMorris** [comment]
Hi, sorry for the delay in responding.  I like the idea in principle.  It sounds like it would be non-trivial to do well, but if you're still interested I could give you some pointers to get you going.

**Comment by martinxyz** [comment]
Just an opinion. If this can be light-weight it could be useful, but on the far side of this there is LeechBlock NG which works quite well (I especially like its "delay" mode of blocking).

**Comment by hrkrshnn** [comment]
> Hi, sorry for the delay in responding. I like the idea in principle. It sounds like it would be non-trivial to do well, but if you're still interested I could give you some pointers to get you going.

I don't plan to create something that would "block" you, just some kind or reminder that you've spent too much time on this site today. For example, a red border around the page.

But I would love to get some pointers about the code.

**Comment by modullar** [comment]
don't know what is the status quo here. but implementing a blocker would be even nicer. so when a user exceeds a certain limit, the website can be blocked.

I can implement this if that is okay
